language: python
python:
  - "3.5"

env:
 - FLASK_CONFIG = "testing"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - mkdir "$HOME/Documents"

install:
  # Note: conda appears to ignore the python spec
  - conda env create --file environment.yml # python=$TRAVIS_PYTHON_VERSION
  - source activate Evert

script:
  - py.test --cov-config .coveragerc --cov=app  app/tests

after_success:
  - coveralls

addons:
  - coveralls:
     repo_token: vJNg5mw9sSdyMaszVlsvGV9tfyAhDKNK1
