name: Evert
dependencies:
 - python=3.5
 - flask==0.12
 - matplotlib==2.0.0
 - Pandas==0.19.2
 - pytables
 - flask-uploads=0.2.1
 - flask-wtf==0.14.2
 - Jinja2==2.8
 - mpld3==0.2
 - pytest==2.8.5
 - WTForms==2.1
 - pip:
    - Flask-Bootstrap==3.3.5.7
    - Flask-Plugins==1.6.1
    - pytest-flask==0.10.0
    - service-identity==16.0.0
    - WTForms-Components==0.10.0
